how-it-works section HTML
compotelover/legendary-waddle pull request #1
Opened 2024-02-28 15:25 UTC by RedisculuS

Adding HTML to section

2024-02-28 16:59 UTC, compotelover requested changes
1. add few spans in ol .step-list-item-descr
2. add image with shadows
3. в 10 рядку ти написала <!-- Will be hidden via CSS -->, мабуть для .header-how-it-works visually hidden, але тоді треба цей напис піднести ближче до нього. Але то вже необов'язково

2024-02-28 17:57 UTC, RedisculuS commented
Додала, пофіксила
Тінь буде вже через css

2024-02-28 22:46 UTC, compotelover requested changes
Залишилося додати цифри 1 2 3 в .counter-value, бо в ol стилі треба обнулити, а циферки додати вручну

2024-02-29 21:31 UTC, RedisculuS commented
В мене така сама проблема як в Олени з картинкою на десктопі.
Їй максимально погано.
Тому почекаю, що тобі ментор відповість і тоді зроблю її гарною.

По всьому іншому чекаю на твій комент :)

2024-03-02 14:24 UTC, compotelover approved these changes

2024-03-02 14:24 UTC, merged