reviews
compotelover/legendary-waddle pull request #4
Opened 2024-02-29 15:16 UTC by oleksandr-sulima

2024-02-29 15:38 UTC, compotelover requested changes
1. Додай background-color для секції, щоб при більш широкому екрані фон зберігався. Наприклад, у мене екран ширше за 1280px і за межами діва у мене білий фон, а не світло-сірий як на діві
2. Онови мейн, в контейнерах мають бути падінги загальні

2024-02-29 16:30 UTC, oleksandr-sulima commented
changes done

2024-03-01 13:00 UTC, oleksandr-sulima commented
pushed fixes, please check

2024-03-02 13:03 UTC, compotelover approved these changes

2024-03-02 13:03 UTC, merged